---
- name: Set Locales in locale.conf
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: '0644'

- name: Set Locales in locale.gen
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales_gen }}"


